language: csharp
solution: ITgestao.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ITgestao.sln
  - nuget install NUnit.framework
  - nuget install NUnit
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release ITgestao.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Tests/bin/Release/Tests.dll
#  - nunit-console Tests/bin/Debug/Tests.dll